apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-gke-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-gke-app
  template:
    metadata:
      labels:
        app: my-gke-app
    spec:
      containers:
      - name: nodejs-app-container
        # Placeholder นี้จะถูกแทนที่โดย GitHub Actions
        image: gcr.io/your-project-id/my-gke-app:latest
        ports:
        - containerPort: 8080
